on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake build .
  test:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake --build .
      - run: ./tests
  coverage:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake --build .
      - run: ./tests
      - run: lcov -t "coverageTests" -o coverage.info -c -d CMakeFiles/lib.dir/Sources/
      - run: genhtml -o report coverage.info
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./report/
  linter:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cppcheck --quiet Sources/ Headers/
      - run: cpplint --verbose=0 Sources/*.c Headers/*.h

  valgrind:
    runs-on: ubuntu-latest
    container: killoboker/gcc-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake --build .
      - run: ./tests
      - run: valgrind --track-origins=yes --leak-check=full --log-file=valgrindLogs.txt ./tests
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./valgrindLogs.txt


